apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logoutput-ns
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: logoutput-claim
        - name: logoutput-configmap-volume
          configMap:
            name: logoutput-configmap
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: logoutput
          image: dermotbg/logoutput:v7.6.3
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "750m"
              memory: "512Mi"
          volumeMounts:
          - name: shared-files
            mountPath: /usr/src/app/files
          - name: logoutput-configmap-volume
            mountPath: /usr/src/app/config
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: logoutput-configmap
                key: MESSAGE
        - name: logtimestamp
          image: dermotbg/logtimestamp:v5
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "750m"
              memory: "512Mi"
          volumeMounts:
          - name: shared-files
            mountPath: /usr/src/app/files