apiVersion: todo/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchlabels:
      app: todo
    template:
      metadata:
        labels:
          app: todo
      spec:
        containers:
          - name: todo
            image: dermotbg/todo:latest