apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: todo-ns
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: todo-files
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todo
          image: PROJECT/IMAGE
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "3000" 
          volumeMounts:
          - name: todo-files
            mountPath: /usr/src/app/files
        - name: todo-image-source
          image: dermotbg/todo-image-source:v0.4
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
          - name: todo-files
            mountPath: /usr/src/app/files