apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logoutput-ns
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      # volumes:
      #   - name: shared-files
      #     persistentVolumeClaim:
      #       claimName: logoutput-claim
      containers:
        - name: pingpong
          image: dermotbg/ping-pong:v7.5.4
          # volumeMounts:
          # - name: shared-files
          #   mountPath: /usr/src/app/files