apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logoutput-ns
  name: pingpong-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      # volumes:
      #   - name: shared-files
      #     persistentVolumeClaim:
      #       claimName: logoutput-claim
      containers:
        - name: pingpong
          image: dermotbg/ping-pong:v7.5.5
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          # volumeMounts:
          # - name: shared-files
          #   mountPath: /usr/src/app/files