apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/rollout.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/autoscaler.yaml
images:
  - name: PROJECT/IMAGE
    newName: dermotbg/todo:v3.9.3