apiVersion: v1
kind: Service
metadata:
  namespace: todo-ns
  name: todo-backend-svc
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000