name: Cleanup Branch

on:
  delete:

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    name: Echo Test
    steps:
      - uses: actions/checkout@v4
      - name: Echo branch
        run: |-
          echo "Event.Ref: ${{ github.event.ref }}"
          echo "Event.Ref_Type: ${{ github.event.ref_type }}"
  