name: Cleanup Branch

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dermotbg-cluster
  GKE_ZONE: europe-west12-a

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    name: Cleanup Environment
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
    
      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
            cluster_name: '${{ env.GKE_CLUSTER }}'
            project_id: '${{ env.PROJECT_ID }}'
            location: '${{ env.GKE_ZONE }}'

      - name: 'Cleanup Resources in Namespace'
        run: |-
          echo "Branch Name: ${{ github.event.ref }}"
          kubectl delete all --all -n ${{ github.event.ref }}


      - name: 'Cleanup Namespace'
        run: |-
          kubectl delete namespace ${{ github.event.ref }} || true
          