name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dermotbg-cluster
  GKE_ZONE: europe-west12-a
  IMAGEFE: todo
  IMAGEBE: todo-backend
  SERVICEFE: todo-dep
  SERVICEBE: todo-backend-dep
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
    
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
    
      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
            cluster_name: '${{ env.GKE_CLUSTER }}'
            project_id: '${{ env.PROJECT_ID }}'
            location: '${{ env.GKE_ZONE }}'

      - name: Build Frontend
        run: docker build --tag "gcr.io/$PROJECT_ID/$IMAGEFE:$BRANCH-$GITHUB_SHA" ./ToDo

      - name: Publish Frontend
        run: docker push "gcr.io/$PROJECT_ID/$IMAGEFE:$BRANCH-$GITHUB_SHA"

      - name: Build Backend
        run: docker build --tag "gcr.io/$PROJECT_ID/$IMAGEBE:$BRANCH-$GITHUB_SHA" ./ToDo-Backend

      - name: Publish Backend
        run: docker push "gcr.io/$PROJECT_ID/$IMAGEBE:$BRANCH-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |-
          cd ToDo/
          kustomize edit set image PROJECT/IMAGE=gcr.io/$PROJECT_ID/$IMAGEFE:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          cd ../ToDo-Backend/
          kustomize edit set image PROJECT/IMAGE=gcr.io/$PROJECT_ID/$IMAGEBE:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl get deployments
          kubectl rollout status deployment $SERVICEFE
          kubectl rollout status deployment $SERVICEBE
          kubectl get services -o wide