apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: todo-ns
  name: todo-pv
spec:
  storageClassName: todo-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/todo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            # - key: kubernetes.io/hostname
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              # - k3d-k3s-default-agent-0
              - europe-west12-a